feat: Likes and Friends
elGordoGato/java-filmorate pull request #4
Opened 2023-06-09 07:24 UTC by elGordoGato

Sprint 10

2023-06-09 20:01 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-10 17:18 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NotFoundException(FILM);
Как я понял все исключения лучше кидать в сервисе, а не в хранилище?

2023-06-10 18:29 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NotFoundException(FILM);
если коротко, то да

2023-06-10 19:45 UTC, FanaticFiz approved these changes

2023-06-10 19:45 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public HashSet<Film> getAll() {
В качестве типа указывай интерфейс `HashSet -> Set`

2023-06-10 19:45 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Optional<Film> removeById(Integer id);
Создание, обновление и удаление зачастую делают `void`

2023-06-11 03:26 UTC, merged